FROM openjdk:8-jre-alpine

MAINTAINER zhaoxiangjie

COPY limits.conf /etc/security/limits.conf
ADD http://192.168.31.209/elasticsearch/elasticsearch-6.7.2.tar.gz /tmp

RUN sed -i "s@dl-cdn.alpinelinux.org@mirrors.aliyun.com@g" /etc/apk/repositories && \
    adduser -h /home/elasticsearch -s /bin/sh -D elasticsearch && \
    echo "elasticsearch:123456" | chpasswd && \
    tar xf /tmp/elasticsearch-6.7.2.tar.gz -C /home/elasticsearch/ && \
    chown -R elasticsearch:elasticsearch  /home/elasticsearch && \
    rm -rf /tmp/elasticsearch-6.7.2.tar.gz

WORKDIR /home/elasticsearch/es/
USER elasticsearch
EXPOSE 9200

CMD ["sh", "-c", "./bin/elasticsearch"]
