FROM xtfs-common:1.6.0-alpine

MAINTAINER zhaoxiangjie

COPY start-dir.sh /
#CMD ["/usr/bin/java", "-ea", \
#     "-cp", "/usr/share/java/xtreemfs.jar:/usr/share/java/jdmkrt.jar:/usr/share/java/jdmktk.jar:/usr/share/java/commons-codec-1.3.jar", \
#     "org.xtreemfs.dir.DIR", "/etc/xos/xtreemfs/dirconfig.properties"]
CMD sh /start-dir.sh
